### PR TITLE
Added compatibility with LobbyInviteOnly Mod

### PR DESCRIPTION
**Pull request by 1A3Dev**
- Made the join button be hidden for invite only lobbies when using the LobbyInviteOnly mod.

### CODE REVIEW

**Comment by AndreyMrovol** [comment]
Hey, thanks for your proposition - my issues with it:
1. When i create a lobby to play with friends, I want to send game invite to `#general` for them to join, so that would destroy my use case
2. You can disable friends/voice channel members from joining you without permission in Discord's Privacy Settings, if that's the problem with your use case
image

I think this idea makes sense (although not for _my_ use case), so my proposition is a config flag (which will be enabled by default) for the "Ask to join" button to be displayed - I think that's the best of both worlds, it will make both use cases possible without any sacrifices from either side (also it fits well with _"fully configurable"_ catchphrase)

**Comment by AndreyMrovol** [comment]
Also, this config flag exists in current (and some previous) version on Thunderstore
image

https://github.com/AndreyMrovol/LethalRichPresence/blob/62f4ddb3df0723af7d6658443e3870e0c1960342/LethalRichPresence/Lifecycle.cs#L118C1-L122C8

**Comment by AndreyMrovol** [comment]
I pushed an update to Thunderstore - check if it fixes your issue

**Comment by AndreyMrovol** [comment]
I submitted _a small refactor_ of your code, and I think it's in the ideal state: it works **flawlessly** with your mod, and the conditions are very clearly defined:

- Ship must be in orbit
- `AllowJoin` must be true
- Party cannot be invite-only
- If `JoinOnlyInPublicLobby` is true, the party must be public

**only then** the `Invite`/`Join` button will show up.

**Comment by 1A3Dev** [comment]
Seems good to me

**Comment by AndreyMrovol** [comment]
I quickly tested returned values with your mod using logger:
`Variables.IsPartyInviteOnly() || (!Variables.IsPartyPublic() && ConfigManager.JoinOnlyInPublicLobby.Value)`

- public lobby: False || (False && False) => false
- friends-only: False || (True && False) => false
- invite-only: True || (True && False) => true

When `JoinOnlyInPublicLobby` is true:

- public lobby: False || (False && True) => false
- friends-only: False || (True && True) => true
- invite-only: True || (True && True) => true

**Comment by AndreyMrovol** [comment]
It all works as intended - thanks a lot for your submission!

**Pull request merged**
